<?xml version="1.0" encoding="utf-8"?><Database Name="HogwartsDatabase" Class="HogwartsDatabaseModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LOCNGO-PC\SQLEXPRESS;Initial Catalog=HogwartsDatabase;User ID=hogwarts_dba" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="HogwartsDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="ArticleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Content" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Article" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentRequest" Member="StudentRequests">
    <Type Name="StudentRequest">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NewFirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NewLastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NewNationality" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NewMMailAddress" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NewHouseName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="RequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="Student_StudentRequest" Member="Student" ThisKey="StudentID" OtherKey="StudentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Course" Member="Courses">
    <Type Name="Course">
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SemesterID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttendeeNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaxCapacity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Course_Session" Member="Sessions" ThisKey="CourseID" OtherKey="CourseID" Type="Session" />
      <Association Name="Course_StudentInCourse" Member="StudentInCourses" ThisKey="CourseID" OtherKey="CourseID" Type="StudentInCourse" />
      <Association Name="Discipline_Course" Member="Discipline" ThisKey="DisciplineID" OtherKey="DisciplineID" Type="Discipline" IsForeignKey="true" />
      <Association Name="Semester_Course" Member="Semester" ThisKey="SemesterID" OtherKey="SemesterID" Type="Semester" IsForeignKey="true" />
      <Association Name="Staff_Course" Member="Staff" ThisKey="StaffID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="StudentNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StaffNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DisciplineNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DepartmentDeanID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Department_Discipline" Member="Disciplines" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Discipline" />
      <Association Name="Department_Staff" Member="Staffs" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Staff" />
      <Association Name="Department_Student" Member="Students" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Student" />
      <Association Name="Staff_Department" Member="Staff" ThisKey="DepartmentDeanID" OtherKey="StaffID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Discipline" Member="Disciplines">
    <Type Name="Discipline">
      <Column Name="DisciplineID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="CreditNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PeriodPerWeek" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Discipline_Course" Member="Courses" ThisKey="DisciplineID" OtherKey="DisciplineID" Type="Course" />
      <Association Name="Department_Discipline" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.House" Member="Houses">
    <Type Name="House">
      <Column Name="HouseID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HouseName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Association Name="House_Student" Member="Students" ThisKey="HouseID" OtherKey="HouseID" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Semester" Member="Semesters">
    <Type Name="Semester">
      <Column Name="SemesterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Time" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Semester_Course" Member="Courses" ThisKey="SemesterID" OtherKey="SemesterID" Type="Course" />
    </Type>
  </Table>
  <Table Name="dbo.Session" Member="Sessions">
    <Type Name="Session">
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SessionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Classroom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weekday" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PeriodNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartingPeriod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Course_Session" Member="Course" ThisKey="CourseID" OtherKey="CourseID" Type="Course" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MmailAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MagicalSecurityNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Female" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_Article" Member="Articles" ThisKey="StaffID" OtherKey="StaffID" Type="Article" />
      <Association Name="Staff_Course" Member="Courses" ThisKey="StaffID" OtherKey="StaffID" Type="Course" />
      <Association Name="Staff_Department" Member="Departments" ThisKey="StaffID" OtherKey="DepartmentDeanID" Type="Department" />
      <Association Name="Department_Staff" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MagicalSecurityNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DepartmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MmailAddress" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Female" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AcquiredCreditNumber" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GradePointAverage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="HouseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Student_StudentRequest" Member="StudentRequests" ThisKey="StudentID" OtherKey="StudentID" Type="StudentRequest" />
      <Association Name="Student_StudentInCourse" Member="StudentInCourses" ThisKey="StudentID" OtherKey="StudentID" Type="StudentInCourse" />
      <Association Name="Department_Student" Member="Department" ThisKey="DepartmentID" OtherKey="DepartmentID" Type="Department" IsForeignKey="true" />
      <Association Name="House_Student" Member="House" ThisKey="HouseID" OtherKey="HouseID" Type="House" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StudentInCourse" Member="StudentInCourses">
    <Type Name="StudentInCourse">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CourseGPA" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Course_StudentInCourse" Member="Course" ThisKey="CourseID" OtherKey="CourseID" Type="Course" IsForeignKey="true" />
      <Association Name="Student_StudentInCourse" Member="Student" ThisKey="StudentID" OtherKey="StudentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
</Database>